### ISSUE TITLE
 Error in UseMethod("mlflow_id"): no applicable method for 'mlflow_id'

### ISSUE THREAD

**Issue by Realsid** [cran/mlflow#1]
While running the [tutorial for R](https://www.mlflow.org/docs/latest/tutorial.html) I am encountering the following error:

> 2019/06/14 10:31:12 INFO mlflow.projects: === Created directory /tmp/tmpyunx_lo4 for downloading remote URIs passed to arguments of type 'path' ===
> 2019/06/14 10:31:12 INFO mlflow.projects: === Created directory /tmp/tmpyunx_lo4 for downloading remote URIs passed to arguments of type 'path' ===
> 2019/06/14 10:31:12 INFO mlflow.projects: === Running command 'Rscript -e "mlflow::mlflow_source('train.R')" --args' in run with ID '4a69a786bd2b42d1930f7c5d91f73301' ===
> 2019/06/14 10:31:12 INFO mlflow.projects: === Running command 'Rscript -e "mlflow::mlflow_source('train.R')" --args' in run with ID '4a69a786bd2b42d1930f7c5d91f73301' ===
> Error in UseMethod("mlflow_id"): no applicable method for 'mlflow_id' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
> 
> 
> Error in UseMethod("mlflow_id"): no applicable method for 'mlflow_id' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
> 
> 
> Error: There is no active run to end.
> Execution halted
> Error: There is no active run to end.
> Execution halted
> 2019/06/14 10:31:17 ERROR mlflow.cli: === Run (ID '4a69a786bd2b42d1930f7c5d91f73301') failed ===
> 2019/06/14 10:31:17 ERROR mlflow.cli: === Run (ID '4a69a786bd2b42d1930f7c5d91f73301') failed ===

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file.
