### ISSUE TITLE
install_mlflow() by setting MLFLOW_PYTHON_BIN and MLFLOW_BIN

### ISSUE THREAD

**Issue by n8shadow** [cran/mlflow#3]
Hi,
I'm working on Azure Databricks and I would like to use mlflow. However, my company is restricting the internet connection such that the required files cannot be downloaded to build up the conda environment.
In the docu I read: 
"Alternatively, you can set MLFLOW_PYTHON_BIN and MLFLOW_BIN environment variables
instead. MLFLOW_PYTHON_BIN should point to python executable and MLFLOW_BIN to
mlflow cli executable."
I don't fully understand how to set these parameters to make use of an existing environment that - to my understanding - should in general be available on Databricks 7.x and what the correct paths (e.g. /dbfs/databricks/...) are.
Any clarification on that would be highly appreciated, thanks in advance!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!
